### ISSUE TITLE
Some iOS map routes don't take a query - how should handle this?

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#101]
An example of this is the /orientation route.

```ruby
map_route(nil, :orientation, :status_bar)
```

The generic route handling code returns a QueryResult, but a `nil` query raises an error (see below).

##### 1. map_route('/orientation', :orientation, :status_bar)

If not '/orientation', then some other indication of what generated the result.

##### 2. map_route('', ...)

YAGNI - would we ever need or want to know that it was call to the /orientation route?  This would probably be important if our routes were versioned e.g. `/api/v2/orientation`.  What version of the API did this hit to produce this result.

##### 3. Don't return a QueryResult

Breaks the current model.  @TobiasRoikjer has already expressed concerns about returning a QueryResult.

#### nil-query error

```ruby
TypeError: can't dup NilClass
	from /Users/moody/git/calabash/lib/calabash/query.rb:92:in `dup'
	from /Users/moody/git/calabash/lib/calabash/query.rb:92:in `new'
	from /Users/moody/git/calabash/lib/calabash/query_result.rb:19:in `initialize'
	from /Users/moody/git/calabash/lib/calabash/query_result.rb:8:in `new'
	from /Users/moody/git/calabash/lib/calabash/query_result.rb:8:in `create'
	from /Users/moody/git/calabash/lib/calabash/ios/routes/route_mixin.rb:53:in `route_success'
	from /Users/moody/git/calabash/lib/calabash/ios/routes/route_mixin.rb:30:in `route_handle_response'
	from /Users/moody/git/calabash/lib/calabash/ios/routes/map_route.rb:9:in `map_route'
```

**Comment by jmoody** [comment]
### Outcome

Option 1.

**Comment by jmoody** [comment]
It turns out that we must pass `nil` because that is what the LPMapRoute expects.

* [**LPMapRoute: convert to ARC**](https://github.com/calabash/calabash-ios-server/pull/177)
* [**iOS: Status Bar API for Cucumber**](#111) 
* 7304567
