### ISSUE TITLE
AndroidManifest.xml does not exist

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#193]
### Reproduce

1. pull the latest from develop

2.
```
$ cd cucumber/android
# Resign if necessary.
$ be calabash console ../../spec/resources/android/xtc-android-sample.apk 
```

### Expected

The console to start.

### Found

```
$ be calabash console ../../spec/resources/android/xtc-android-sample.apk 
Test server does not exist. Creating test server.
/Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1391:in `initialize': No such file or directory @ rb_sysopen - /Users/moody/git/calabash/calabash/lib/calabash/android/lib/AndroidManifest.xml (Errno::ENOENT)
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1391:in `open'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/build/builder.rb:57:in `block (2 levels) in build'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/build/builder.rb:55:in `chdir'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/build/builder.rb:55:in `block in build'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/build/builder.rb:54:in `build'
        from /Users/moody/git/calabash/calabash/lib/calabash/cli/console.rb:30:in `parse_console_arguments!'
        from /Users/moody/git/calabash/calabash/bin/calabash:70:in `parse_arguments!'
        from /Users/moody/git/calabash/calabash/bin/calabash:25:in `evaluate'
        from /Users/moody/git/calabash/calabash/bin/calabash:99:in `<top (required)>'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/calabash:23:in `load'
        from /Users/moody/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/calabash:23:in `<main>'
```

### Notes

I grabbed the AndroidManifest.xml from the [calabash-android repo](https://github.com/calabash/calabash-android/blob/master/ruby-gem/test-server/AndroidManifest.xml) and installed locally.

I was able to start the console.

But what happened?  I see this file is git ignored, but part of the gemspec.  Should it not be ignored?

**Comment by TobiasRoikjer** [comment]
@jmoody You need to build the test-server if you are running from the github source. e.g. rake android:build
