### ISSUE TITLE
Handling adb "rm failed for -f. No such file or directory"

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#194]
As you may recall, my Samsung S3 is having a problem installing apps.

```
irb(main):003:0> ensure_app_installed
RuntimeError: Could not install app 'com.xamarin.xtcandroidsample.test': rm failed for -f, No such file or directory
        from /Users/moody/git/calabash/calabash/lib/calabash/android/device.rb:849:in `adb_install_app'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/device.rb:682:in `_ensure_app_installed'
        from /Users/moody/git/calabash/calabash/lib/calabash/device.rb:66:in `ensure_app_installed'
        from /Users/moody/git/calabash/calabash/lib/calabash/android/device.rb:688:in `_ensure_app_installed'
        from /Users/moody/git/calabash/calabash/lib/calabash/device.rb:66:in `ensure_app_installed'
        from /Users/moody/git/calabash/calabash/lib/calabash/life_cycle.rb:57:in `ensure_app_installed'
        from (irb):3
        from /Users/moody/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```

Can we catch this message in adb.command?

**Comment by TobiasRoikjer** [comment]
@jmoody Good. I'll change this to
```
adb push x y
adb shell pm install [flags] y
adb rm y
```
