### ISSUE TITLE
Wordpress: Adding a self-hosted site is flickering

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#207]
```
 Scenario: Adding a self-hosted site               # features/login.feature:6
    Given I am on the login screen                  # features/step_definitions/login_steps.rb.rb:29
    Then I should be able to add a self-hosted site # features/step_definitions/login_steps.rb.rb:34
      Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError)
      ./features/android/pages/login_page.rb:49:in `toggle_self_hosted_site'
      ./features/android/pages/login_page.rb:34:in `enable_self_hosted_site'
      ./features/step_definitions/login_steps.rb.rb:35:in `/^I should be able to add a self\-hosted site$/'
      features/login.feature:8:in `Then I should be able to add a self-hosted site'
```

**Comment by TobiasRoikjer** [comment]
@jmoody We should dismiss the keyboard

**Comment by jmoody** [comment]
Fixed by: **Ensure we hide keyboard before tapping login** #205 ?
