### ISSUE TITLE
Stack-traces in cli tool upon exit

### ISSUE THREAD

**Issue by krukow** [calabash/calabash#217]
When an error happens in the CLI tool I see a long stacktrace with Calabash internals. I'd like for this to be disabled by default. Instead of this:

```
calabash run agile2015.apk
Test server does not exist. Creating test server.
/Users/krukow/samples/agile/agile2015.apk is not signed with any of the available keystores.
Tried the following keystores:
/Users/krukow/.android/debug.keystore

You can resign the app with /Users/krukow/.android/debug.keystore by running:
      calabash resign /Users/krukow/samples/agile/agile2015.apk

Notice that resigning an app might break some functionality.
Getting a copy of the certificate used when the app was build will in general be more reliable.
/Users/krukow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-1.9.9.pre2/lib/calabash/android/build/builder.rb:46:in `build': /Users/krukow/samples/agile/agile2015.apk is not signed with any of the available keystores (Calabash::Android::Build::BuildError)
	from /Users/krukow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-1.9.9.pre2/lib/calabash/cli/run.rb:38:in `parse_run_arguments!'
	from /Users/krukow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-1.9.9.pre2/bin/calabash:74:in `parse_arguments!'
	from /Users/krukow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-1.9.9.pre2/bin/calabash:25:in `evaluate'
	from /Users/krukow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-1.9.9.pre2/bin/calabash:99:in `<top (required)>'
...
```

I'd like to see something similar to this:
```
calabash run agile2015.apk
Test server does not exist. Creating test server.
/Users/krukow/samples/agile/agile2015.apk is not signed with any of the available keystores.
Tried the following keystores:
/Users/krukow/.android/debug.keystore

You can resign the app with /Users/krukow/.android/debug.keystore by running:
      calabash resign /Users/krukow/samples/agile/agile2015.apk

Notice that resigning an app might break some functionality.
Getting a copy of the certificate used when the app was build will in general be more reliable.

(To get more verbose log output use the '-v' option or set the environment variable DEBUG=1)
```

We should consider asking the user if they want Calabash to generating a keystore and resign - and then go ahead and do it for them making the run command succeed.

**Comment by TobiasRoikjer** [comment]
@krukow I agree on this issue. I don't think resigning when given a parameter is a good idea. 

Should we just `exit 1` instead of raising?

**Comment by krukow** [comment]
yes - but do print the stack trace if in debug mode.
