### ISSUE TITLE
iOS:  "Execution expired" instead of timeout message

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#277]
### Error

```
  @location
  Scenario: Location alert is dismissed    # features/permissions.feature:10
    When I touch the Location Services row # features/step_definitions/shared_steps.rb:30
    Then Calabash should dismiss the alert # features/step_definitions/alerts_steps.rb:138
 execution expired (Calabash::IOS::RouteError)
 ./features/step_definitions/alerts_steps.rb:6:in `alert_exists?'
```

### Step

```
  4     def alert_exists?(alert_title=nil)
  5       if alert_title.nil?
  6         res = uia('uia.alert() != null')
  7       else
  8         if ios6?
  9           res = uia("uia.alert().staticTexts()['#{alert_title}'].label()")
 10         else
 11           res = uia("uia.alert().name() == '#{alert_title}'")
 12         end
 13       end
 14         
 15       if res.empty?
 16         false
 17       else
 18         res.first
 19       end
 20     end 


138 Then(/^Calabash should dismiss the alert$/) do
139   sleep 1.0
140   timeout = 1.0
141   message = "Timed out after #{timeout} seconds for alert to be dismissed"
142   wait_for(message, {:timeout => timeout}) do
143     !alert_exists?
144   end
145 end
```

**Comment by jmoody** [comment]
If you change the condition to this:

```
 uia('uia.alert() == null')
```

Then you get this:

```
   Then Calabash should dismiss the alert # features/step_definitions/alerts_steps.rb:138
 execution expired (Calabash::IOS::RouteError)
 ./features/step_definitions/alerts_steps.rb:143:in `block (2 levels) in <top (required)>'
 ./features/step_definitions/alerts_steps.rb:142:in `/^Calabash should dismiss the alert$/'
 features/permissions.feature:12:in `Then Calabash should dismiss the alert'
```

**Comment by jmoody** [comment]
The problem appears to be with the `onAlert()` JavaScript dismissing the an alert.

There must be a significant delay _after_  the alert is dismissed before any UIA calls can be made or you must make a recalibration call (like after rotating the device).
