### ISSUE TITLE
Can't install app on iOS Simulator : uninitialized constant RunLoop::Simctl::Bridge

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#289]
Hello
I have Yosemite 10.10.3, Xcode 6.2
I just install Calabash gem 2.0.0pre4.
I want to install my app (or any other, same problem) on the iOS simulator from the console but I have an error : 

admin$ CAL_DEVICE_ID="iPhone 5 (8.1 Simulator)" calabash console /Users/admin/Documents/builds/myapp-cal.app 
Running irb...

 =>  Useful Methods  <=
     ids => List all the visible ids.
 classes => List all the visible classes.
    tree => The app's visible view hierarchy.
    copy => Copy console commands to the Clipboard.
   clear => Clear the console.
 verbose => Turn debug logging on.
   quiet => Turn debug logging off.

Calabash 2.0.0.pre4 says: 'Uti, non abuti.'
irb(main):001:0> install_app
RuntimeError: Could not install #<Application /Users/admin/Documents/builds/myapp-cal.app> on #<Simulator: iPhone 5 (8.1) F1F91024-122A-461B-8A9B-F19A3C224637 i386>: uninitialized constant RunLoop::Simctl::Bridge
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:625:in `rescue in install_app_on_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:614:in `install_app_on_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:450:in `_install_app'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:73:in `install_app'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/life_cycle.rb:70:in `install_app'
	from (irb):1
	from /Users/admin/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

Note that on my Mac with El Capitain and Xcode 7, I don't have this problem, the exact same app is ok (and the others one)

My gem list on my Yosemite Mac : 
appium_lib (6.0.0)
ast (2.0.0)
astrolabe (1.3.0)
awesome_print (1.6.1)
bigdecimal (1.2.6)
blankslate (2.1.2.4)
builder (3.2.2)
bundle (0.0.1)
bundler (1.9.4)
bundler-unload (1.0.2)
calabash (2.0.0.pre4)
calabash-common (0.0.2)
CFPropertyList (2.3.1)
childprocess (0.5.6, 0.5.5)
chunky_png (1.3.4)
clipboard (1.0.6)
coderay (1.1.0)
command_runner_ng (0.1.0)
cucumber (2.0.0)
cucumber-core (1.1.3)
data_magic (0.21, 0.20)
diff-lcs (1.2.5)
edn (1.1.0)
escape (0.0.4)
executable-hooks (1.3.2)
eyes_selenium (2.20.0, 2.13.0)
faker (1.4.3)
faraday (0.9.1)
ffi (1.9.8)
flog (4.3.2)
gem-wrappers (1.2.7)
geocoder (1.2.9)
gherkin (2.12.2)
hirb (0.7.3)
httparty (0.13.3)
httpclient (2.6.0.1)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.2, 1.8.1)
luffa (1.1.0)
method_source (0.8.2)
mini_portile (0.6.0)
multi_json (1.11.0)
multi_test (0.1.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
nokogiri (1.6.3.1)
oily_png (1.2.0, 1.1.2)
oj (2.12.9)
page-object (1.0.3)
page_navigation (0.9)
parser (2.2.2.2, 2.2.0.3)
parslet (1.5.0)
powerpack (0.1.1, 0.1.0)
pry (0.10.1)
psych (2.0.8)
rack (1.6.4)
rack-protection (1.5.3)
rainbow (2.0.0)
rake (10.4.2)
rdoc (4.2.0)
require_relative (1.0.3)
retriable (2.1.0, 2.0.2)
rspec (3.2.0)
rspec-core (3.2.3, 3.2.2)
rspec-expectations (3.2.1, 3.2.0)
rspec-mocks (3.2.1)
rspec-support (3.2.2)
rubocop (0.30.0)
ruby-progressbar (1.7.5)
ruby_parser (3.6.6, 3.6.5)
rubygems-bundler (1.4.4)
rubyzip (1.1.7)
run_loop (1.5.6)
rvm (1.11.3.9)
selenium-webdriver (2.45.0)
sexp_processor (4.5.1, 4.5.0)
sim_launcher (0.4.13)
sinatra (1.4.6)
slop (3.6.0)
slowhandcuke (0.0.3)
syntax (1.2.0)
thor (0.19.1)
tilt (2.0.1)
toml (0.1.2)
watir-ng (1.0.0)
watir-scroll (0.1.0)
watir-webdriver (0.7.0)
websocket (1.2.2, 1.2.1)
yaml-lint (0.0.4)
yml_reader (0.5)

Thanks for helping !

**Comment by distortia** [comment]
When I dropped my run loop to 1.5.1, I was able to run simulators again.

**Comment by jmoody** [comment]
Yeah, the run-loop version is out of sync with this library.  I don't have time at the moment to update.  I have started a local branch.

**Comment by jmoody** [comment]
I am making progress on this fix.

**Comment by ericzered** [comment]
Thanks a lot, I understand now.
I will now only user Xcode 7 and El Capitain because it's working great with that
